version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
      - | 
        if [ "$ENV" = "prod" ]; then
          pip install --upgrade awscli
        fi
  build:
    commands:
      - npm run build
      
  post_build:
    commands:
      - | 
        if [ "$ENV" = "prod" ]; then
          aws cloudfront create-invalidation --distribution-id E2R5MDIA8O7VAI --paths "/*"
        fi
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'  
